name: 'Deploy OpenTelemetry'
on:
  push:
    branches: [main, master, dev]
    paths:
      - .github/workflows/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: NPM Deploy
    concurrency:
      group: otel-deploy-job
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.21.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: Authorization=Api-Token ${{ secrets.DYNATRACE_API_TOKEN }}
          OTEL_SERVICE_NAME: otel-mcp-package-build
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.DEPLOY_OBSERVABILITY_TOKEN }}","${{ secrets.DYNATRACE_API_TOKEN }}"]'
      - uses: plengauer/opentelemetry-github/actions/instrument/deploy@v5.21.0
        with:
          github_token: '${{ secrets.DEPLOY_OBSERVABILITY_TOKEN }}'
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: Authorization=Api-Token ${{ secrets.DYNATRACE_API_TOKEN }}
          OTEL_SERVICE_NAME: otel-mcp-package-build
          OTEL_RESOURCE_ATTRIBUTES: service.version=${{ steps['package-version'].outputs.version }},deployment.environment=${{ (github.ref_name == 'main' && 'production') || 'development' }}
    permissions:
      actions: read
